version: "3.1"

services:
  front:
    image: lashby8/ecg-fe:latest
    restart: always
    ports:
      - "80:80"
  back:
    image: lashby8/ecg-be:latest
    restart: always
    ports:
      - "8001:8001"
  converter:
    image: lashby8/ecg-converter:latest
    restart: always
    ports:
      - "8002:8002"
  model:
    image: lashby8/ecg-model:latest
    restart: always
    ports:
      - "8003:8003"
