version: "3.1"

services:
  front:
    image: lashby8/ecg-fe:latest
    restart: always
    ports:
      - "80:80"
  back:
    image: lashby8/ecg-be:latest
    restart: always
    env_file:
      - ".env"
  converter:
    image: lashby8/ecg-converter:latest
    restart: always
    env_file:
      - ".env"
  model:
    image: lashby8/ecg-model:latest
    restart: always
    env_file:
      - ".env"
    ports:
      - "8003:8003"
