version: "3.1"

services:
  front:
    image: lashby8/ecg-fe:latest
    restart: always
    ports:
      - "${FRONT_PORT}:80"
  back:
    image: lashby8/ecg-be:latest
    restart: always
    ports:
      - "${BACK_PORT}:80"
  converter:
    image: lashby8/ecg-converter:latest
    restart: always
    ports:
      - "${CONVERTER_PORT}:80"
  model:
    image: lashby8/ecg-model:latest
    restart: always
    ports:
      - "${MODEL_PORT}:80"
