name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Install Necessary Tools for Running Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.8
        id: go
      - uses: actions/setup-node@v1
        with:
          node-version: '10.20.1'

      - name: Get dependencies, Build, Run Tests for back
        run: |
          cd ./back
          go get -d -v -t
          go build .
          go test -cover ./...
      - name: Get dependencies, Build, Run Tests for converter
        run: |
          cd ./converter
          go get -d -v -t
          go build .
          go test -cover ./...
      - name: Get dependencies, Build, Run Tests for front
        run: |
          cd ./front
          npm install
          CI=true npm test
