name: Docker Images CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Dockerization
    steps:
      - uses: actions/checkout@v2
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.0.2
        env:
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
        with:
          host: $HOST_NAME
          username: $USERNAME
          key: $SSH_PRIVATE_KEY
          port: $PORT
          script: ls -la
