name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Dockerization
    steps:
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: Building Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME_FE }}
        run:
          docker build --no-cache -t $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:latest ./front
#       - name: Push Docker Container to Registry
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME_FE }}
#         run: docker push $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:latest
