name: Docker Images CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Dockerization
    steps:
      - uses: actions/checkout@v2
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - name: SSH Commands
        env:
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
        run:  sudo mkdir ~/.ssh && sudo touch ~/.ssh/id_rsa && sudo echo $SSH_PRIVATE_KEY >> ~/.ssh/id_rsa && ssh -p $PORT $USERNAME@$HOST_NAME ls -la
