name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: App Dockerization
    steps:
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#         run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          run: ls -la
      - name: Building Docker Image
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run:
          docker build --no-cache -t $DOCKER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:latest ./front
      - name: Push Docker Container to Registry
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run: docker push $DOCKER_REGISTRY_URL/$CONTAINER_IMAGE_NAME:latest
